version: '3.7'
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask
    restart: unless-stopped
    environment:
      FLASK_ENV: "production"
      FLASK_DEBUG: "False"
      FLASK_PORT: 5000
      DB_HOST: mongo
      DB_PORT: 27017
      DB_USERNAME: dbuser
      DB_PASSWORD: password
      DB_NAME: app
      REDIS_HOST: redis
      REDIS_PORT: 6379
    env_file:
      - .env
    volumes:
      - appdata:/home/worker
    depends_on:
      - redis
      - mongo
    networks:
      - frontend
      - backend

  mongo:
    image: mongo:latest
    restart: unless-stopped
    command: ["--auth"]
    env_file:
      - .env.dev
    volumes:
      - ./docker/mongo/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - mongodata:/data/db
    ports:
    - '27017-27019:27017-27019'
    networks:
      - backend

  webserver:
    build: nginx
    container_name: nginx
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      APP_NAME: "webserver"
      APP_DEBUG: "true"
      SERVICE_NAME: "webserver"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginxdata:/var/log/nginx
    depends_on:
      - flask
    networks:
      - frontend

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - redisdata:/data/redis
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
    - "6379:6379"
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  redisdata:
    driver: local
  mongodata:
    driver: local
  appdata:
    driver: local
  nginxdata:
    driver: local